### ISSUE TITLE
Question: Documentation / HowTo / Support Discord?

### ISSUE THREAD

**Issue by cryptochrome** [OFRBG/TsukiBot#12]
Hi there,

is there an official Discord server for the bot? Is there any documentation other than what's in the GitHub Wiki? Things like the @File Perms role it creates on joining, no clue what that does. Also, would love to read how the timed susbscriptions with ETH payments works. 

Thanks

**Comment by OFRBG** [comment]
Hello, I'm working on adding docs to the project. I started with the KLI intro. I'm working on publishing something more readable than `.tbhelp`.
The role File Perms is for mods to be given to people who should be allowed to send files that aren't images or video. If a user _without_ <File Perms> send a `.rar` or `.exe`, TsukiBot deletes the message.
The timed subscriptions are down for the time being, since I really need to work on the interface at tsukibot.com and the network fees are flying. You can still create the timed subs semi-automatically by doing:

> .tb subrole Patrons
> .tb sub @cryptochrome Patrons

You can use a name other than Patrons, and you need to make sure you @mention the correct user. It currently expires after 30 days, if you want to test it out.

**Comment by cryptochrome** [comment]
Thanks. Why sending files at all? What's the file sending feature all about?

**Comment by OFRBG** [comment]
File sending can be a problem. Scammers might drop a virus and a poor soul might download and run. Sounds like a sad way to lose crypto. For crypto it's never safe enough, especially in public channels. I'm working on the wiki, by the way.

**Comment by cryptochrome** [comment]
So are you controlling Discord's "attach files" and "embed links" permissions through the bot?

**Comment by OFRBG** [comment]
Links aren't checked. Only files are checked for their extension. You can see the line that does this here: https://github.com/OFRBG/TsukiBot/blob/78b36f4a71cc9b60072f02bc0c23d6fffacd59e6/bot.js#L1138 This permission comes from being able to delete messages.

**Comment by cryptochrome** [comment]
Awesome, thank you! :)

**Comment by OFRBG** [comment]
No problem. Any questions, feel free to keep asking.
